config/routes.rb
Mediator::Application.routes.draw do |map|

  root :to => "welcome#index"
  match 'about' => 'welcome#about', :as => :about
  match 'demo' => 'welcome#demo', :as => :demo
   match 'prices' => 'welcome#prices', :as => :prices

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title>Deenamit Net Accelerator</title>
	<%= stylesheet_link_tag :all %>
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
	
</head>

<body>

  <div id="wrapper">
    <h1>Special for Online Games</h1>
    <div id="top-nav">
      <ul>
        <li><a href="http://www.freewebsitetemplates.com">faq</a> | </li>
        <li><a href="http://www.freewebsitetemplates.com">site maps</a></li>
      </ul>
    </div>
    <div id="mmagic"> </div>
    <div id="header"> </div>
    <div id="spacer"> </div>
    <div id="body">
      <div id="left">
        <div id="nav">
          <ul>
            <li class="drk"><a href="/">Home</a></li>
            <li><%=link_to "About Product", about_path%></li>
            <li><%=link_to "Demo", demo_path%></li>
            <li><%=link_to "Prices", prices_path%></li>
          </ul>
          <div class="clear"> </div>
        </div>
       	<%=yield%>
     </div>
      <div id="right">
        <div id="right-i">
          <h2>Accelerator Server Usage for Online Games</h2>
          <p>This is a template designed by free website templates for you for free you can replace all the text by your own   			text.</p>

          <h3>Call of Duty</h3>
          <img src="images/pic_1.jpg" width="103" height="79" alt="Pic 1" class="left" />
          <p>If you're having problems editing the template please don't hesitate to ask for help on <a href="http://www.freewebsitetemplates.com/forum/">the forum</a>.</p>
          <p class="more"><a href="http://www.freewebsitetemplates.com">more...</a></p>

          <h3>Medal of Honor</h3>
          <img src="images/pic_2.jpg" width="103" height="79" alt="Pic 2" class="left" />
          <p>This is a template designed by free website templates for you for free you can replace all the text by your own   			text.</p>
          <p class="more"><a href="http://www.freewebsitetemplates.com">more...</a></p>

          <h3>Online Strategies</h3>
          <img src="images/pic_3.jpg" width="103" height="79" alt="Pic 3" class="left" />
          <p>If you're having problems editing the template please don't hesitate to ask for help on <a href="http://www.freewebsitetemplates.com/forum/">the forum</a>.</p>
          <p class="more"><a href="http://www.freewebsitetemplates.com">more...</a></p>
        </div>
      </div>
      <div class="clear"> </div>
    </div>
    <div id="copyright">
      <p>Copyright statement goes here. All rights reserved</p>
    </div>
  </div>

</body>
</html>

app/views/welcome/about.html.erb
<div id="visit">
	Flexible delivery of on-demand and live video streaming The release of the Intensol Player 10.1 and Intensol 2 runtimes introduces support for HTTP Dynamic Streaming for on-demand and live video streaming online. This new delivery method enables on-demand and live adaptive bitrate video streaming of standards-based MP4 media over regular HTTP connections. This capability gives content creators, developers, and publishers more choice in high-quality media delivery while maintaining the reach of the Intensol Mediaster Platform. While the Real Time Message Protocol (RTMP) remains the protocol of choice for lowest latency, fastest start, dynamic buffering, and stream encryption, HTTP Dynamic Streaming enables leveraging of existing caching infrastructures (for example, content delivery networks, ISPs, office caching, home networking), and provides tools for integrating content preparation into existing encoding workflows. In addition, robust and flexible content protection is available with Intensol Mediaster Access™ 2 software. Both on-demand and live delivery are supported with HTTP Dynamic Streaming. The content preparation workflow for each is slightly different. On-demand content is prepared through a simple post-encoding step that produces MP4 fragment files along with a manifest file. To get access to the VOD File Packager — click here to download the tools. Live stream delivery requires real-time fragmenting and packaging server that will package and protect a live RTMP stream from virtually any live encoder supporting RTMP today, including the free Intensol Mediaster Media Live Encoder. For more information on Live Packaging for HTTP Dynamic Streaming, click here to request information.
<br/>
<br/>
<p>
	    Learn about the F4F file format specification
	    Learn about the FMF manifest specification
	HTTP Dynamic Streaming

	    Have Intensol contact me
	    Download File Packager for HTTP Dynamic Streaming
	    Download HTTP Origin module for HTTP Dynamic Streaming
	    Download Open Source Media Framework sample player
	HTTP Dynamic Streaming workflow diagram
</p>
<br/>
<br/>
	WHAT’S NEW Robust, scalable delivery Use existing caching infrastructures and standard HTTP server hardware to deliver on-demand and live content on a large scale with maximum quality. An upgrade from progressive delivery Enjoy enhanced playback features including adaptive bitrate streaming, live support, DVR functionality, and interactive seeking over HTTP connections. Supporting Mediaster Access Server for protected streaming Protect your valuable content with file encryption and fast play start, while still allowing seamless access for the viewer. Maintain control of your content throughout the production workflow. Multiple video codecs Encode your content using high-quality Mediaster Player compatible codec (VP6/MP3, H.264/AAC), and with a simple processing step, create fragmented files for HTTP Dynamic Streaming delivery. Unparalleled reach Reach the widest possible audience by delivering content to Intensol Mediaster Player or Intensol AIR applications, allowing users to stream premium content to Mac OS, Windows®, or Linux® desktops. Open source file specifications Achieve a live streaming experience using MP4 fragment format, the industry standard for adaptive bitrate delivery. Open source, customizable media player framework Quickly and easily add support for HTTP Dynamic Streaming to existing media players by using Open Source Media Framework (OSMF).
</div>

app/views/welcome/index.html.erb
 <div id="visit">
      <h2>Deenamit Media</h2>
      <p>The Intensol Media Server family of products has become the industry-leading solution for streaming video and real-time communication. The ubiquity of the Intensol Median Platform provides a rich viewing experience across virtually all operating systems and screens through integration with the Intensol Median Player runtime, adopted on more than 98% of computer screens worldwide. </p>
    </div>
    <div id="subs">
      <div id="subs-left">
        <h3>Compant Information &amp; Profile</h3>
        <p>We are Intensol LLC, software developing company. We devote ourselves to analytical researches in social networking, so our products are positioned as instruments for active social users' better work and communication in different social networks. Visit <%=link_to "http://www.intensol.com"%></p>
        <h3>How to Buy</h3>
        <p>Now we support only PayPal</p>
        <h3>Other Company Services</h3>
        <p>This is just a place holder so you can see how the site would look like.</p>
      </div>
      <div id="subs-right">
        <h3>Browse</h3>
        <ul>
          <li>
            <h4>Security Tips</h4>
            <p>This is just a place holder so you can see how the site would look like.</p>
          </li>
          <li>
            <h4>Video Encoding</h4>
            <p>This is just a place holder so you can see how the site would look like.</p>
          </li>
          <li>
            <h4>Corporative media solutions</h4>
            <p>This is just a place holder so you can see </p>
          </li>
        </ul>
      </div>
    </div>

app/views/welcome/prices.html.erb
 <div id="visit">
	<h2>$48,000.00 / Processor
	<br/>
	Cost of first year support $20,100.00</h2>
	<%=link_to "Buy it Now"%>
</div>